# Generated by Django 4.2.18 on 2025-03-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="song", old_name="title", new_name="name",),
    ]
