# Generated by Django 4.2.18 on 2025-03-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_title_song_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="artist",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
